"use strict";
exports.__esModule = true;
var Profesional_1 = require("./Profesional");
var DenzelWashigton;
DenzelWashigton = new Profesional_1.Profesional("Dezel Washigton", 66, "Masculino", 80, 185, "negro", "Marrones", "Yorsay", false, "USA", 2, "Actor/Director");
var RobertDowneyJr;
RobertDowneyJr = new Profesional_1.Profesional("Robert Downey Jr", 55, "Masculino", 78, 172, "Castaño", "Marrones", "Caniche", false, "USA", 0, "Actor/Productor/Cantante");
var ScarlettJohansson;
ScarlettJohansson = new Profesional_1.Profesional("Scarllet Johansson", 36, "Femenino", 58, 163, "Pelirrojo", "Azul", "Pomerania", false, "USA", 0, "Actriz/Cantante/Modelo");
var KeiraKnightley;
KeiraKnightley = new Profesional_1.Profesional("Keira Knightley", 34, "Femenino", 57, 170, "Castaño", "Verdes", "Chow Chow", false, "Inglesa", 0, "Actriz/Modelo");
var SeanConnery;
SeanConnery = new Profesional_1.Profesional("Sean Connery", 90, "Masculino", 90, 190, "Blanco", "Marrones", "Shar Pei", true, "Inglesa", 1, "Actor/Productor");
var WillSmith;
WillSmith = new Profesional_1.Profesional("Will Smith", 52, "Masculino", 90, 188, "Negro", "Marron", "Doberman", false, "USA", 2, "Actor/Rapero/Productor de cine/Productor de TV/Productor discografico");
var ChrisHemsworth;
ChrisHemsworth = new Profesional_1.Profesional("Chris Hemsworth", 36, "Masculino", 84, 191, "Rubio", "Azules", "Pastor Ovejero Australiano", false, "Australiano", 2, "Actor");
var ChrisEvans;
ChrisEvans = new Profesional_1.Profesional("Chris Evans", 38, "Masculino", 91, 182, "Rubio", "Azules", "Golden Retriever", false, "Estadounidense", 3, "Actor/Modelo/Director de cine");
var HarrisonFord;
HarrisonFord = new Profesional_1.Profesional("Harrison Ford", 77, "Masculino", 81, 185, "Moreno", "Marrón", "Shih Tzu", false, "Estadounidense", 0, "Actor/Productor de cine");
var LeonardoDiCaprio;
LeonardoDiCaprio = new Profesional_1.Profesional("Leonardo DiCaprio", 45, "Masculino", 78, 183, "Rubio", "Azules", "Bichón maltés", false, "Estadounidense", 1, "Actor/Productor de cine/Ambientalista/Guionista");
ScarlettJohansson.mostrarAtributosProfesional();
